"""Kabuk's own animations and habits."""

from ._kit import scene  # noqa: F401  (used by his signature animations)

NAME = "Kabuk"
HABITS = ['phone', 'tip']             # shared emotes he falls back to; his own ones are added too
ACCEPTS_JOINT = 0.75           # chance he takes the joint when Snoop passes it
REFUSAL = ''

TEXT = {c: "y" for c in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!?.,-"}
CASH = {"$": "g", "▭": "g"}

EMOTES: dict[str, dict] = {
    "kabuk-cash": scene("licking his thumb and counting a fat stack, bills flying", [
        ["   one..        ",
         "  (¬‿¬)ﾉ▭       ",
         "  /|▓▓▓| ▭▭▭    ",
         "   /  \\ ▭▭▭▭▭  "],
        ["   two..   $    ",
         "  (¬‿¬)ﾉ  ▭     ",
         "  /|▓▓▓| ▭▭▭    ",
         "   /  \\ ▭▭▭▭   "],
        ["  $  a million  ",
         "  ($‿$)ﾉ ▭  $   ",
         "  /|▓▓▓| ▭▭     ",
         "   /  \\ ▭▭▭    "],
        [" $  $ CHA-CHING ",
         " \\($▽$)/   $  $",
         "   |▓▓▓|  ▭     ",
         "   /  \\  ▭▭    "],
    ], {**TEXT, **CASH}),
    "kabuk-chart": scene("shilling his coin: chart pumps to the moon, then the rug gets pulled", [
        ["  ▁▂▃     buy!  ",
         "  (¬‿¬)ﾉ        ",
         "  /|▓▓▓|        ",
         "   /  \\         "],
        ["  ▁▂▃▅▇█  MOON  ",
         "  ($▽$)/        ",
         "  /|▓▓▓|        ",
         "   /  \\         "],
        ["  ▁▂▃▅▇█▼  uh   ",
         "  (°_°);        ",
         "  /|▓▓▓|\\       ",
         "   /  \\         "],
        ["  ▁▂▃▅▇█▼▼▼ RUG ",
         "  (ಥ_ಥ);;       ",
         "  \\|▓▓▓|/       ",
         "   /  \\  hodl.. "],
    ], {**TEXT, "▁": "g", "▂": "g", "▃": "g", "▅": "g", "▇": "g", "█": "g", "▼": "e", ";": "c", "$": "g"}),
    "kabuk-suitcase": scene("flashing open his trench coat full of shady deals", [
        ["  psst. hey you ",
         "  (¬‿¬)         ",
         "  ▐|▓▓▓|▌       ",
         "   /  \\         "],
        ["  wanna buy a.. ",
         "  (¬‿¬)         ",
         " ◇╱|▓▓▓|╲◇      ",
         "   /  \\         "],
        ["  rolex? 5 bux  ",
         "  (ˆ‿ˆ)ﾉ◷       ",
         "◇◇╱|▓▓▓|╲◇◇     ",
         " ◷ /  \\ ◷      "],
        ["  used kidney?  ",
         "  (¬‿¬)ﾉ$       ",
         "  ▐|▓▓▓|▌       ",
         "   /  \\         "],
    ], {**TEXT, **CASH, "◇": "y", "◷": "y", "▐": "w", "▌": "w", "╱": "w", "╲": "w"}),
    "kabuk-chain": scene("swinging his gold chain around, bling glinting (it's brass)", [
        ["         ✧      ",
         "  (¬‿¬)ﾉ        ",
         "  /|▓▓▓| o      ",
         "   /  \\  ◆     "],
        ["            ✦   ",
         "  (¬‿¬)ﾉ o◆     ",
         "  /|▓▓▓|        ",
         "   /  \\         "],
        ["  ✧ 24 karat ✧  ",
         "  (¬▽¬)ﾉ        ",
         "  /|▓▓▓| o      ",
         "   /  \\ ◆       "],
        [" ✦  (its brass) ",
         "  (¬‿¬)ﾉ o◆  ✦  ",
         "  /|▓▓▓|        ",
         "   /  \\         "],
    ], {**TEXT, "✧": "y", "✦": "y", "◆": "y", "(": ".", ")": "."}),
    "kabuk-calculator": scene("punching a calculator, the number only goes up, dollar eyes", [
        ["         [  420]",
         "  (¬‿¬)ﾉ [789]  ",
         "  /|▓▓▓| [456]  ",
         "   /  \\  [123]  "],
        ["         [ 6.9K]",
         "  (¬▽¬)ﾍ [789]  ",
         "  /|▓▓▓| [456]  ",
         "   /  \\  [123]  "],
        ["         [ 420K]",
         "  ($_$)ﾉ [789]  ",
         "  /|▓▓▓| [456]  ",
         "   /  \\  [123]  "],
        [" RICH  [$$$$$$]",
         " \\($▽$)/ [789]  ",
         "   |▓▓▓| [456]  ",
         "   /  \\  [123]  "],
    ], {"[": "m", "]": "m", **{c: "c" for c in "0123456789.K"}, "$": "g",
        "R": "y", "I": "y", "C": "y", "H": "y"}),
}
