"""Pas's own animations and habits."""

from ._kit import scene  # noqa: F401  (used by his signature animations)

NAME = "Pas"
HABITS = ['hype', 'flex']             # shared emotes he falls back to; his own ones are added too
ACCEPTS_JOINT = 0.5           # chance he takes the joint when Snoop passes it
REFUSAL = "too hyped already, doesn't need it"

SHOUT = {ch: "e" for ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ!':0"}
HYPE = {ch: "y" for ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ!"}

EMOTES: dict[str, dict] = {
    "pas-megaphone": scene("SCREAMING into a megaphone, the sound waves getting bigger", [
        ["    GO GO GO    ",
         " (ˆ▽ˆ)⊲         ",
         " \\|▓▓▓|ﾉ        ",
         "  /   \\         "],
        ["   LET'S GOOO   ",
         " (ﾟﾛﾟ)⊲ }       ",
         " \\|▓▓▓|ﾉ        ",
         "  <   \\         "],
        ["  LET'S GOOOOO! ",
         " (ﾟﾛﾟ)⊲ } }     ",
         " \\|▓▓▓|ﾉ        ",
         "  /   >         "],
        ["LET'S GOOOOOOO!!",
         " (≧▽≦)⊲ } } }}  ",
         " \\|▓▓▓|ﾉ        ",
         "  <   >         "],
    ], {**SHOUT, "⊲": "m", "}": "y"}),
    "pas-confetti": scene("jumping up and down while confetti rains on everything", [
        [" * ✦ · ✧ * · ✦  ",
         "  \\(ˆ▽ˆ)/       ",
         "    |▓▓▓|       ",
         "    /   \\       "],
        ["  ✧ * ✦ · * ✧ · ",
         "  \\(≧▽≦)/ YEAH  ",
         "    |▓▓▓|    ✦  ",
         "   _/   \\_  *   "],
        [" · ✦ * ✧ · ✦ *  ",
         " * \\(ˆoˆ)/  ·   ",
         "  ✧ |▓▓▓| *     ",
         "  · /   \\   ✧ · "],
        [" ✧ · ✦ * ✧ · ✦ *",
         "  \\(≧▽≦)/ WOOO  ",
         " ·  |▓▓▓|  ✦ *  ",
         "*·✧_/ * \\_·✦*·✧ "],
    ], {"*": "r", "✦": "r", "·": "r", "✧": "r", **HYPE}),
    "pas-airhorn": scene("blasting an airhorn, BWAAA getting louder every frame", [
        ["       ?        ",
         "  (ˆ▽ˆ)ﾉ▯⊲      ",
         "   /|▓▓▓|       ",
         "    /   \\       "],
        ["   BWA          ",
         "  (≧▽≦)ﾉ▯⊲}     ",
         "   /|▓▓▓|       ",
         "    /   \\       "],
        ["   BWAAAAA      ",
         "  (>▽<)ﾉ▯⊲} }   ",
         "   /|▓▓▓|       ",
         "    <   >       "],
        [" BWAAAAAAAAAA!! ",
         "  (ﾟﾛﾟ)ﾉ▯⊲} } } ",
         "   /|▓▓▓|       ",
         "   _/   \\_      "],
    ], {**SHOUT, "▯": "e", "⊲": "m", "}": "y", "?": "y"}),
    "pas-pompoms": scene("cheerleading with pompoms: GIMME AN F, GIMME AN I, FIX IT", [
        ["  GIMME AN F!   ",
         " ✺\\(ˆ▽ˆ)/✺      ",
         "    |▓▓▓|       ",
         "    /   \\       "],
        ["  ✺       ✺     ",
         "   \\(ˆoˆ)/  F!  ",
         "    |▓▓▓|       ",
         "    <   >       "],
        ["  GIMME AN I!   ",
         "  ✺=(ˆ▽ˆ)=✺     ",
         "    |▓▓▓|       ",
         "    /   \\       "],
        ["✺  FIX IT!!!  ✺ ",
         " ✺\\(≧▽≦)/✺      ",
         "    |▓▓▓|       ",
         "   _/   \\_      "],
    ], {"✺": "r", "=": "r", **HYPE}),
    "pas-sprint": scene("sprinting in place at full speed, going absolutely nowhere", [
        ["   GO GO GO     ",
         "   (ò▽ó)        ",
         " = /|▓▓▓|\\      ",
         " =  /   >       "],
        ["    GO GO GO    ",
         "   (ò▽ó)ﾉ       ",
         " = \\|▓▓▓|/      ",
         " =  <   \\  ·    "],
        ["  FASTER!!      ",
         "  (>▽<)         ",
         "== /|▓▓▓|\\      ",
         "==  /   >  °    "],
        ["SPEED: 0 KMH!!! ",
         "  (≧▽≦)         ",
         "===\\|▓▓▓|/      ",
         "=== <   \\ ° ·   "],
    ], {**SHOUT, "=": "s", "°": "s", "·": "s"}),
}
